from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import threading


class Ui_MainWindow_add_income_expense(object):
    def setupUi(self, MainWindow_add_income_expense, refresh):
        MainWindow_add_income_expense.setObjectName("MainWindow_add_income_expense")
        MainWindow_add_income_expense.resize(900, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow_add_income_expense)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_monthly_contribution = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_monthly_contribution.sizePolicy().hasHeightForWidth())
        self.lineEdit_monthly_contribution.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_monthly_contribution.setFont(font)
        self.lineEdit_monthly_contribution.setObjectName("lineEdit_monthly_contribution")
        self.gridLayout.addWidget(self.lineEdit_monthly_contribution, 7, 2, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 19, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 29, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 25, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 21, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 13, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 30, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        self.lineEdit_donation = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_donation.sizePolicy().hasHeightForWidth())
        self.lineEdit_donation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_donation.setFont(font)
        self.lineEdit_donation.setObjectName("lineEdit_donation")
        self.gridLayout.addWidget(self.lineEdit_donation, 13, 2, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 4, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem5, 20, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 17, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 15, 1, 1, 3)
        self.lineEdit_miscellaneous = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_miscellaneous.sizePolicy().hasHeightForWidth())
        self.lineEdit_miscellaneous.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_miscellaneous.setFont(font)
        self.lineEdit_miscellaneous.setObjectName("lineEdit_miscellaneous")
        self.gridLayout.addWidget(self.lineEdit_miscellaneous, 21, 2, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 1, 1, 3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 26, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem7, 18, 1, 1, 1)
        self.comboBox_year = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_year.sizePolicy().hasHeightForWidth())
        self.comboBox_year.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_year.setFont(font)
        self.comboBox_year.setObjectName("comboBox_year")
        self.gridLayout.addWidget(self.comboBox_year, 3, 2, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem8, 8, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem9, 14, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem10, 6, 1, 1, 1)
        self.lineEdit_disaster_allowance = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_disaster_allowance.sizePolicy().hasHeightForWidth())
        self.lineEdit_disaster_allowance.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_disaster_allowance.setFont(font)
        self.lineEdit_disaster_allowance.setObjectName("lineEdit_disaster_allowance")
        self.gridLayout.addWidget(self.lineEdit_disaster_allowance, 19, 2, 1, 2)
        spacerItem11 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem11, 28, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(42)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 11, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem12, 16, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem13, 10, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem14, 12, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 1, 1, 1)
        self.lineEdit_admit_fine = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_admit_fine.sizePolicy().hasHeightForWidth())
        self.lineEdit_admit_fine.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_admit_fine.setFont(font)
        self.lineEdit_admit_fine.setObjectName("lineEdit_admit_fine")
        self.gridLayout.addWidget(self.lineEdit_admit_fine, 9, 2, 1, 2)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem16, 29, 3, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem17, 0, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem18, 22, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 27, 1, 1, 1)
        self.lineEdit_death_allowance = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_death_allowance.sizePolicy().hasHeightForWidth())
        self.lineEdit_death_allowance.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_death_allowance.setFont(font)
        self.lineEdit_death_allowance.setObjectName("lineEdit_death_allowance")
        self.gridLayout.addWidget(self.lineEdit_death_allowance, 17, 2, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 9, 1, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save.sizePolicy().hasHeightForWidth())
        self.pushButton_save.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 29, 2, 1, 1)
        self.lineEdit_form = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_form.sizePolicy().hasHeightForWidth())
        self.lineEdit_form.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_form.setFont(font)
        self.lineEdit_form.setObjectName("lineEdit_form")
        self.gridLayout.addWidget(self.lineEdit_form, 11, 2, 1, 2)
        spacerItem19 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem19, 24, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 23, 1, 1, 3)
        self.lineEdit_previous_balance = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_previous_balance.sizePolicy().hasHeightForWidth())
        self.lineEdit_previous_balance.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_previous_balance.setFont(font)
        self.lineEdit_previous_balance.setObjectName("lineEdit_previous_balance")
        self.gridLayout.addWidget(self.lineEdit_previous_balance, 25, 2, 1, 2)
        self.lineEdit_new_balance = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_new_balance.sizePolicy().hasHeightForWidth())
        self.lineEdit_new_balance.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_new_balance.setFont(font)
        self.lineEdit_new_balance.setObjectName("lineEdit_new_balance")
        self.gridLayout.addWidget(self.lineEdit_new_balance, 27, 2, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow_add_income_expense.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_add_income_expense)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_add_income_expense)
        MainWindow_add_income_expense.setTabOrder(self.comboBox_year, self.lineEdit_monthly_contribution)
        MainWindow_add_income_expense.setTabOrder(self.lineEdit_monthly_contribution, self.lineEdit_admit_fine)
        MainWindow_add_income_expense.setTabOrder(self.lineEdit_admit_fine, self.lineEdit_form)
        MainWindow_add_income_expense.setTabOrder(self.lineEdit_form, self.lineEdit_donation)
        MainWindow_add_income_expense.setTabOrder(self.lineEdit_donation, self.lineEdit_death_allowance)
        MainWindow_add_income_expense.setTabOrder(self.lineEdit_death_allowance, self.lineEdit_disaster_allowance)
        MainWindow_add_income_expense.setTabOrder(self.lineEdit_disaster_allowance, self.lineEdit_miscellaneous)
        MainWindow_add_income_expense.setTabOrder(self.lineEdit_miscellaneous, self.lineEdit_previous_balance)
        MainWindow_add_income_expense.setTabOrder(self.lineEdit_previous_balance, self.lineEdit_new_balance)
        MainWindow_add_income_expense.setTabOrder(self.lineEdit_new_balance, self.pushButton_save)

        self.pushButton_save.clicked.connect(lambda : self.save(refresh))

        self.assign()

    def retranslateUi(self, MainWindow_add_income_expense):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_add_income_expense.setWindowTitle(_translate("MainWindow_add_income_expense", "Add Income Expense Miscellaneous"))
        self.label_10.setText(_translate("MainWindow_add_income_expense", "Disaster Allowance"))
        self.label_12.setText(_translate("MainWindow_add_income_expense", "Previous Bank Balance"))
        self.label_11.setText(_translate("MainWindow_add_income_expense", "Miscellaneous"))
        self.label_7.setText(_translate("MainWindow_add_income_expense", "Donation"))
        self.label_9.setText(_translate("MainWindow_add_income_expense", "Death Allowance"))
        self.label_8.setText(_translate("MainWindow_add_income_expense", "Expense"))
        self.label_5.setText(_translate("MainWindow_add_income_expense", "Income"))
        self.label.setText(_translate("MainWindow_add_income_expense", "Add Income Expense"))
        self.label_6.setText(_translate("MainWindow_add_income_expense", "Form"))
        self.label_2.setText(_translate("MainWindow_add_income_expense", "Year"))
        self.label_3.setText(_translate("MainWindow_add_income_expense", "Monthly Contribution"))
        self.label_13.setText(_translate("MainWindow_add_income_expense", "New Bank Balance"))
        self.label_4.setText(_translate("MainWindow_add_income_expense", "Admit/Fine"))
        self.pushButton_save.setText(_translate("MainWindow_add_income_expense", "Save"))
        self.label_14.setText(_translate("MainWindow_add_income_expense", "Bank Balance"))

    def assign(self):
        conn = sqlite3.connect("RSKT.db")
        cur = conn.cursor()
        sql = "SELECT * FROM receipt"
        cur.execute(sql)
        items = cur.fetchall()
        conn.commit()
        conn.close()

        years = [i[5].split("/")[1] for i in items]
        years = list(set(years))
        years.sort()
        for year in years:
            self.comboBox_year.addItem(year)
        self.comboBox_year.setEditable(True)

        self.set_defaults()

        self.comboBox_year.activated.connect(lambda : self.get_data(items))

    def set_defaults(self):
        self.lineEdit_monthly_contribution.setText("0")
        self.lineEdit_admit_fine.setText("0")
        self.lineEdit_form.setText("0")
        self.lineEdit_donation.setText("0")
        self.lineEdit_death_allowance.setText("0")
        self.lineEdit_disaster_allowance.setText("0")
        self.lineEdit_miscellaneous.setText("0")
        self.lineEdit_previous_balance.setText("0")
        self.lineEdit_new_balance.setText("0")

    def save(self, refresh_income_expense_window):
        try:
            year = self.comboBox_year.currentText()
            monthly_contribution = int(self.lineEdit_monthly_contribution.text())
            admit_fine = int(self.lineEdit_admit_fine.text())
            form = int(self.lineEdit_form.text())
            donation = int(self.lineEdit_donation.text())
            death_allowance = int(self.lineEdit_death_allowance.text())
            disaster_allowance = int(self.lineEdit_disaster_allowance.text())
            miscellaneous = int(self.lineEdit_miscellaneous.text())
            previous_balance = int(self.lineEdit_previous_balance.text())
            new_balance = int(self.lineEdit_new_balance.text())
        except Exception as e:
            message = QtWidgets.QMessageBox(QtWidgets.QMessageBox.Critical, "Error", f"{str(e)}")
            message.exec_()

        conn = sqlite3.connect("RSKT.db")
        cur = conn.cursor()
        sql = """INSERT INTO income_expense VALUES (
                        :year, 
                        :monthly_contribution, 
                        :admit_fine, 
                        :form, 
                        :donation, 
                        :death_allowance, 
                        :disaster_allowance, 
                        :miscellaneous, 
                        :previous_balance, 
                        :new_balance
        )"""
        try:
            cur.execute(sql, {
                "year": year,
                "monthly_contribution": monthly_contribution,
                "admit_fine": admit_fine,
                "form": form,
                "donation": donation,
                "death_allowance": death_allowance,
                "disaster_allowance": disaster_allowance,
                "miscellaneous": miscellaneous,
                "previous_balance": previous_balance,
                "new_balance": new_balance
            })
            conn.commit()
            message = QtWidgets.QMessageBox(QtWidgets.QMessageBox.Information, "Success", f"Information Saved")
            message.exec_()
            threading.Thread(target=refresh_income_expense_window).start()
            self.set_defaults()
        except Exception as e:
            message = QtWidgets.QMessageBox(QtWidgets.QMessageBox.Critical, "Error", f"{str(e)}")
            message.exec_()
        finally:
            conn.close()

    def get_data(self, items):
        year = self.comboBox_year.currentText()

        monthly_contribution = 0

        for item in items:
            if item[5].split("/")[1] == year and item[4] == "Due/Current/Advance":
                monthly_contribution = monthly_contribution + item[3]
        self.lineEdit_monthly_contribution.setText(str(monthly_contribution))

        admit_fine = 0

        for item in items:
            if item[5].split("/")[1] == year and item[4] == "Admit/Fine":
                admit_fine = admit_fine + item[3]
        self.lineEdit_admit_fine.setText(str(admit_fine))





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_add_income_expense = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_add_income_expense()
    ui.setupUi(MainWindow_add_income_expense)
    MainWindow_add_income_expense.show()
    sys.exit(app.exec_())
