# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splash_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_splash_screen(object):
    def setupUi(self, MainWindow_splash_screen):
        MainWindow_splash_screen.setObjectName("MainWindow_splash_screen")
        MainWindow_splash_screen.resize(400, 200)
        self.centralwidget = QtWidgets.QWidget(MainWindow_splash_screen)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(80)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow_splash_screen.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_splash_screen)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_splash_screen)

    def retranslateUi(self, MainWindow_splash_screen):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_splash_screen.setWindowTitle(_translate("MainWindow_splash_screen", "MainWindow"))
        self.label.setText(_translate("MainWindow_splash_screen", "RSKT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_splash_screen = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_splash_screen()
    ui.setupUi(MainWindow_splash_screen)
    MainWindow_splash_screen.show()
    sys.exit(app.exec_())
